apiVersion: v1
kind: Service
metadata:
  name: bpmn-mysql
  labels:
    app: bpmn
spec:
  ports:
    - port: 3308
  selector:
    app: bpmn
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: bpmn-mysql
  labels:
    app: bpmn
spec:
  selector:
    matchLabels:
      app: bpmn
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bpmn
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw2mysql
        ports:
        - containerPort: 3308
          name: mysql
        volumeMounts:
        - name: bpmn-mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: bpmn-mysql-storage
        PersistentVolumeClaim:
          claimName: bpmn-mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bpmn-mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi