apiVersion: v1
kind: Service
metadata:
  name: bpmn-node
  labels:
    app: bpmn
spec:
  type: LoadBalancer
  ports:
  - port: 8787
    protocol: TCP
  selector:
    app: bpmn
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: bpmn-node
  labels:
    app: bpmn
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bpmn
      tier: nodejs
  template:
    metadata:
      labels:
        app: bpmn
        tier: nodejs
    spec:
      containers:
      - name: bpmn
        image: itsfrdm/bpmn-node:1.0.0
        env:
        - name: DATABASE_HOST
          value: bpmn-mysql
        - name: DB_PASSWORD
          value: pw2mysql
        ports:
        - containerPort: 8686
          name: bpmn
       